//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaMedica.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/ClinicaClass.usuario")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClinicaMedica.ServiceReference1.Nutricionista NutricionistaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenhaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClinicaMedica.ServiceReference1.TipoUsuario TipoUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoUsuario {
            get {
                return this.CodigoUsuarioField;
            }
            set {
                if ((this.CodigoUsuarioField.Equals(value) != true)) {
                    this.CodigoUsuarioField = value;
                    this.RaisePropertyChanged("CodigoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClinicaMedica.ServiceReference1.Nutricionista Nutricionista {
            get {
                return this.NutricionistaField;
            }
            set {
                if ((object.ReferenceEquals(this.NutricionistaField, value) != true)) {
                    this.NutricionistaField = value;
                    this.RaisePropertyChanged("Nutricionista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Senha {
            get {
                return this.SenhaField;
            }
            set {
                if ((object.ReferenceEquals(this.SenhaField, value) != true)) {
                    this.SenhaField = value;
                    this.RaisePropertyChanged("Senha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClinicaMedica.ServiceReference1.TipoUsuario TipoUsuario {
            get {
                return this.TipoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoUsuarioField, value) != true)) {
                    this.TipoUsuarioField = value;
                    this.RaisePropertyChanged("TipoUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Nutricionista", Namespace="http://schemas.datacontract.org/2004/07/ClinicaClass.nutricionista")]
    [System.SerializableAttribute()]
    public partial class Nutricionista : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BairroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoNutricionistaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CpfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CrnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataNascimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoCivilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UfField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bairro {
            get {
                return this.BairroField;
            }
            set {
                if ((object.ReferenceEquals(this.BairroField, value) != true)) {
                    this.BairroField = value;
                    this.RaisePropertyChanged("Bairro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Celular {
            get {
                return this.CelularField;
            }
            set {
                if ((object.ReferenceEquals(this.CelularField, value) != true)) {
                    this.CelularField = value;
                    this.RaisePropertyChanged("Celular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cep {
            get {
                return this.CepField;
            }
            set {
                if ((object.ReferenceEquals(this.CepField, value) != true)) {
                    this.CepField = value;
                    this.RaisePropertyChanged("Cep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cidade {
            get {
                return this.CidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.CidadeField, value) != true)) {
                    this.CidadeField = value;
                    this.RaisePropertyChanged("Cidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoNutricionista {
            get {
                return this.CodigoNutricionistaField;
            }
            set {
                if ((this.CodigoNutricionistaField.Equals(value) != true)) {
                    this.CodigoNutricionistaField = value;
                    this.RaisePropertyChanged("CodigoNutricionista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cpf {
            get {
                return this.CpfField;
            }
            set {
                if ((object.ReferenceEquals(this.CpfField, value) != true)) {
                    this.CpfField = value;
                    this.RaisePropertyChanged("Cpf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Crn {
            get {
                return this.CrnField;
            }
            set {
                if ((object.ReferenceEquals(this.CrnField, value) != true)) {
                    this.CrnField = value;
                    this.RaisePropertyChanged("Crn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataNascimento {
            get {
                return this.DataNascimentoField;
            }
            set {
                if ((this.DataNascimentoField.Equals(value) != true)) {
                    this.DataNascimentoField = value;
                    this.RaisePropertyChanged("DataNascimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Endereco {
            get {
                return this.EnderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoField, value) != true)) {
                    this.EnderecoField = value;
                    this.RaisePropertyChanged("Endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoCivil {
            get {
                return this.EstadoCivilField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoCivilField, value) != true)) {
                    this.EstadoCivilField = value;
                    this.RaisePropertyChanged("EstadoCivil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observacao {
            get {
                return this.ObservacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacaoField, value) != true)) {
                    this.ObservacaoField = value;
                    this.RaisePropertyChanged("Observacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((this.SexoField.Equals(value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefone {
            get {
                return this.TelefoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoneField, value) != true)) {
                    this.TelefoneField = value;
                    this.RaisePropertyChanged("Telefone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uf {
            get {
                return this.UfField;
            }
            set {
                if ((object.ReferenceEquals(this.UfField, value) != true)) {
                    this.UfField = value;
                    this.RaisePropertyChanged("Uf");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoUsuario", Namespace="http://schemas.datacontract.org/2004/07/ClinicaClass.tipoUsuario")]
    [System.SerializableAttribute()]
    public partial class TipoUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoTipoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoTipoUsuario {
            get {
                return this.CodigoTipoUsuarioField;
            }
            set {
                if ((this.CodigoTipoUsuarioField.Equals(value) != true)) {
                    this.CodigoTipoUsuarioField = value;
                    this.RaisePropertyChanged("CodigoTipoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Paciente", Namespace="http://schemas.datacontract.org/2004/07/ClinicaClass.paciente")]
    [System.SerializableAttribute()]
    public partial class Paciente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AtividadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoPacienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CpfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataNascimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char SexoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Atividade {
            get {
                return this.AtividadeField;
            }
            set {
                if ((object.ReferenceEquals(this.AtividadeField, value) != true)) {
                    this.AtividadeField = value;
                    this.RaisePropertyChanged("Atividade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoPaciente {
            get {
                return this.CodigoPacienteField;
            }
            set {
                if ((this.CodigoPacienteField.Equals(value) != true)) {
                    this.CodigoPacienteField = value;
                    this.RaisePropertyChanged("CodigoPaciente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cpf {
            get {
                return this.CpfField;
            }
            set {
                if ((object.ReferenceEquals(this.CpfField, value) != true)) {
                    this.CpfField = value;
                    this.RaisePropertyChanged("Cpf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataNascimento {
            get {
                return this.DataNascimentoField;
            }
            set {
                if ((this.DataNascimentoField.Equals(value) != true)) {
                    this.DataNascimentoField = value;
                    this.RaisePropertyChanged("DataNascimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Endereco {
            get {
                return this.EnderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoField, value) != true)) {
                    this.EnderecoField = value;
                    this.RaisePropertyChanged("Endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((this.SexoField.Equals(value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Consulta", Namespace="http://schemas.datacontract.org/2004/07/ClinicaClass.consulta")]
    [System.SerializableAttribute()]
    public partial class Consulta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoConsultaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataConsultaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HistoricoFamiliarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MedidasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClinicaMedica.ServiceReference1.Nutricionista NutricionistaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObjetivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClinicaMedica.ServiceReference1.Paciente PacienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PressaoArterialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProblemaSaudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RestricoesAlimentaresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsoMedicamentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Altura {
            get {
                return this.AlturaField;
            }
            set {
                if ((object.ReferenceEquals(this.AlturaField, value) != true)) {
                    this.AlturaField = value;
                    this.RaisePropertyChanged("Altura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoConsulta {
            get {
                return this.CodigoConsultaField;
            }
            set {
                if ((this.CodigoConsultaField.Equals(value) != true)) {
                    this.CodigoConsultaField = value;
                    this.RaisePropertyChanged("CodigoConsulta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataConsulta {
            get {
                return this.DataConsultaField;
            }
            set {
                if ((this.DataConsultaField.Equals(value) != true)) {
                    this.DataConsultaField = value;
                    this.RaisePropertyChanged("DataConsulta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HistoricoFamiliar {
            get {
                return this.HistoricoFamiliarField;
            }
            set {
                if ((object.ReferenceEquals(this.HistoricoFamiliarField, value) != true)) {
                    this.HistoricoFamiliarField = value;
                    this.RaisePropertyChanged("HistoricoFamiliar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Medidas {
            get {
                return this.MedidasField;
            }
            set {
                if ((object.ReferenceEquals(this.MedidasField, value) != true)) {
                    this.MedidasField = value;
                    this.RaisePropertyChanged("Medidas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClinicaMedica.ServiceReference1.Nutricionista Nutricionista {
            get {
                return this.NutricionistaField;
            }
            set {
                if ((object.ReferenceEquals(this.NutricionistaField, value) != true)) {
                    this.NutricionistaField = value;
                    this.RaisePropertyChanged("Nutricionista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Objetivo {
            get {
                return this.ObjetivoField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjetivoField, value) != true)) {
                    this.ObjetivoField = value;
                    this.RaisePropertyChanged("Objetivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observacao {
            get {
                return this.ObservacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacaoField, value) != true)) {
                    this.ObservacaoField = value;
                    this.RaisePropertyChanged("Observacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClinicaMedica.ServiceReference1.Paciente Paciente {
            get {
                return this.PacienteField;
            }
            set {
                if ((object.ReferenceEquals(this.PacienteField, value) != true)) {
                    this.PacienteField = value;
                    this.RaisePropertyChanged("Paciente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Peso {
            get {
                return this.PesoField;
            }
            set {
                if ((object.ReferenceEquals(this.PesoField, value) != true)) {
                    this.PesoField = value;
                    this.RaisePropertyChanged("Peso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PressaoArterial {
            get {
                return this.PressaoArterialField;
            }
            set {
                if ((object.ReferenceEquals(this.PressaoArterialField, value) != true)) {
                    this.PressaoArterialField = value;
                    this.RaisePropertyChanged("PressaoArterial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProblemaSaude {
            get {
                return this.ProblemaSaudeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProblemaSaudeField, value) != true)) {
                    this.ProblemaSaudeField = value;
                    this.RaisePropertyChanged("ProblemaSaude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RestricoesAlimentares {
            get {
                return this.RestricoesAlimentaresField;
            }
            set {
                if ((object.ReferenceEquals(this.RestricoesAlimentaresField, value) != true)) {
                    this.RestricoesAlimentaresField = value;
                    this.RaisePropertyChanged("RestricoesAlimentares");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsoMedicamento {
            get {
                return this.UsoMedicamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.UsoMedicamentoField, value) != true)) {
                    this.UsoMedicamentoField = value;
                    this.RaisePropertyChanged("UsoMedicamento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Servico")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Logar", ReplyAction="http://tempuri.org/IService1/LogarResponse")]
        ClinicaMedica.ServiceReference1.Usuario Logar(ClinicaMedica.ServiceReference1.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Logar", ReplyAction="http://tempuri.org/IService1/LogarResponse")]
        System.Threading.Tasks.Task<ClinicaMedica.ServiceReference1.Usuario> LogarAsync(ClinicaMedica.ServiceReference1.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarTodosPacientes", ReplyAction="http://tempuri.org/IService1/ListarTodosPacientesResponse")]
        ClinicaMedica.ServiceReference1.Paciente[] ListarTodosPacientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarTodosPacientes", ReplyAction="http://tempuri.org/IService1/ListarTodosPacientesResponse")]
        System.Threading.Tasks.Task<ClinicaMedica.ServiceReference1.Paciente[]> ListarTodosPacientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarTodosPacientesPorNome", ReplyAction="http://tempuri.org/IService1/ListarTodosPacientesPorNomeResponse")]
        ClinicaMedica.ServiceReference1.Paciente[] ListarTodosPacientesPorNome(string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarTodosPacientesPorNome", ReplyAction="http://tempuri.org/IService1/ListarTodosPacientesPorNomeResponse")]
        System.Threading.Tasks.Task<ClinicaMedica.ServiceReference1.Paciente[]> ListarTodosPacientesPorNomeAsync(string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarPaciente", ReplyAction="http://tempuri.org/IService1/BuscarPacienteResponse")]
        ClinicaMedica.ServiceReference1.Paciente BuscarPaciente(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarPaciente", ReplyAction="http://tempuri.org/IService1/BuscarPacienteResponse")]
        System.Threading.Tasks.Task<ClinicaMedica.ServiceReference1.Paciente> BuscarPacienteAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InserirConsulta", ReplyAction="http://tempuri.org/IService1/InserirConsultaResponse")]
        void InserirConsulta(ClinicaMedica.ServiceReference1.Consulta consulta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InserirConsulta", ReplyAction="http://tempuri.org/IService1/InserirConsultaResponse")]
        System.Threading.Tasks.Task InserirConsultaAsync(ClinicaMedica.ServiceReference1.Consulta consulta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditarConsulta", ReplyAction="http://tempuri.org/IService1/EditarConsultaResponse")]
        void EditarConsulta(ClinicaMedica.ServiceReference1.Consulta consulta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditarConsulta", ReplyAction="http://tempuri.org/IService1/EditarConsultaResponse")]
        System.Threading.Tasks.Task EditarConsultaAsync(ClinicaMedica.ServiceReference1.Consulta consulta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExcluirConsulta", ReplyAction="http://tempuri.org/IService1/ExcluirConsultaResponse")]
        void ExcluirConsulta(int codigoConsulta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExcluirConsulta", ReplyAction="http://tempuri.org/IService1/ExcluirConsultaResponse")]
        System.Threading.Tasks.Task ExcluirConsultaAsync(int codigoConsulta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarConsulta", ReplyAction="http://tempuri.org/IService1/BuscarConsultaResponse")]
        ClinicaMedica.ServiceReference1.Consulta BuscarConsulta(int codigoConsulta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarConsulta", ReplyAction="http://tempuri.org/IService1/BuscarConsultaResponse")]
        System.Threading.Tasks.Task<ClinicaMedica.ServiceReference1.Consulta> BuscarConsultaAsync(int codigoConsulta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RetornaConsulta", ReplyAction="http://tempuri.org/IService1/RetornaConsultaResponse")]
        ClinicaMedica.ServiceReference1.Consulta RetornaConsulta(ClinicaMedica.ServiceReference1.Consulta consulta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RetornaConsulta", ReplyAction="http://tempuri.org/IService1/RetornaConsultaResponse")]
        System.Threading.Tasks.Task<ClinicaMedica.ServiceReference1.Consulta> RetornaConsultaAsync(ClinicaMedica.ServiceReference1.Consulta consulta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarTodasConsultas", ReplyAction="http://tempuri.org/IService1/ListarTodasConsultasResponse")]
        ClinicaMedica.ServiceReference1.Consulta[] ListarTodasConsultas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarTodasConsultas", ReplyAction="http://tempuri.org/IService1/ListarTodasConsultasResponse")]
        System.Threading.Tasks.Task<ClinicaMedica.ServiceReference1.Consulta[]> ListarTodasConsultasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarTodasConsultasPorPaciente", ReplyAction="http://tempuri.org/IService1/ListarTodasConsultasPorPacienteResponse")]
        ClinicaMedica.ServiceReference1.Consulta[] ListarTodasConsultasPorPaciente(int codigoPaciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarTodasConsultasPorPaciente", ReplyAction="http://tempuri.org/IService1/ListarTodasConsultasPorPacienteResponse")]
        System.Threading.Tasks.Task<ClinicaMedica.ServiceReference1.Consulta[]> ListarTodasConsultasPorPacienteAsync(int codigoPaciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        ClinicaMedica.ServiceReference1.CompositeType GetDataUsingDataContract(ClinicaMedica.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ClinicaMedica.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(ClinicaMedica.ServiceReference1.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ClinicaMedica.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ClinicaMedica.ServiceReference1.IService1>, ClinicaMedica.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClinicaMedica.ServiceReference1.Usuario Logar(ClinicaMedica.ServiceReference1.Usuario usuario) {
            return base.Channel.Logar(usuario);
        }
        
        public System.Threading.Tasks.Task<ClinicaMedica.ServiceReference1.Usuario> LogarAsync(ClinicaMedica.ServiceReference1.Usuario usuario) {
            return base.Channel.LogarAsync(usuario);
        }
        
        public ClinicaMedica.ServiceReference1.Paciente[] ListarTodosPacientes() {
            return base.Channel.ListarTodosPacientes();
        }
        
        public System.Threading.Tasks.Task<ClinicaMedica.ServiceReference1.Paciente[]> ListarTodosPacientesAsync() {
            return base.Channel.ListarTodosPacientesAsync();
        }
        
        public ClinicaMedica.ServiceReference1.Paciente[] ListarTodosPacientesPorNome(string nome) {
            return base.Channel.ListarTodosPacientesPorNome(nome);
        }
        
        public System.Threading.Tasks.Task<ClinicaMedica.ServiceReference1.Paciente[]> ListarTodosPacientesPorNomeAsync(string nome) {
            return base.Channel.ListarTodosPacientesPorNomeAsync(nome);
        }
        
        public ClinicaMedica.ServiceReference1.Paciente BuscarPaciente(int codigo) {
            return base.Channel.BuscarPaciente(codigo);
        }
        
        public System.Threading.Tasks.Task<ClinicaMedica.ServiceReference1.Paciente> BuscarPacienteAsync(int codigo) {
            return base.Channel.BuscarPacienteAsync(codigo);
        }
        
        public void InserirConsulta(ClinicaMedica.ServiceReference1.Consulta consulta) {
            base.Channel.InserirConsulta(consulta);
        }
        
        public System.Threading.Tasks.Task InserirConsultaAsync(ClinicaMedica.ServiceReference1.Consulta consulta) {
            return base.Channel.InserirConsultaAsync(consulta);
        }
        
        public void EditarConsulta(ClinicaMedica.ServiceReference1.Consulta consulta) {
            base.Channel.EditarConsulta(consulta);
        }
        
        public System.Threading.Tasks.Task EditarConsultaAsync(ClinicaMedica.ServiceReference1.Consulta consulta) {
            return base.Channel.EditarConsultaAsync(consulta);
        }
        
        public void ExcluirConsulta(int codigoConsulta) {
            base.Channel.ExcluirConsulta(codigoConsulta);
        }
        
        public System.Threading.Tasks.Task ExcluirConsultaAsync(int codigoConsulta) {
            return base.Channel.ExcluirConsultaAsync(codigoConsulta);
        }
        
        public ClinicaMedica.ServiceReference1.Consulta BuscarConsulta(int codigoConsulta) {
            return base.Channel.BuscarConsulta(codigoConsulta);
        }
        
        public System.Threading.Tasks.Task<ClinicaMedica.ServiceReference1.Consulta> BuscarConsultaAsync(int codigoConsulta) {
            return base.Channel.BuscarConsultaAsync(codigoConsulta);
        }
        
        public ClinicaMedica.ServiceReference1.Consulta RetornaConsulta(ClinicaMedica.ServiceReference1.Consulta consulta) {
            return base.Channel.RetornaConsulta(consulta);
        }
        
        public System.Threading.Tasks.Task<ClinicaMedica.ServiceReference1.Consulta> RetornaConsultaAsync(ClinicaMedica.ServiceReference1.Consulta consulta) {
            return base.Channel.RetornaConsultaAsync(consulta);
        }
        
        public ClinicaMedica.ServiceReference1.Consulta[] ListarTodasConsultas() {
            return base.Channel.ListarTodasConsultas();
        }
        
        public System.Threading.Tasks.Task<ClinicaMedica.ServiceReference1.Consulta[]> ListarTodasConsultasAsync() {
            return base.Channel.ListarTodasConsultasAsync();
        }
        
        public ClinicaMedica.ServiceReference1.Consulta[] ListarTodasConsultasPorPaciente(int codigoPaciente) {
            return base.Channel.ListarTodasConsultasPorPaciente(codigoPaciente);
        }
        
        public System.Threading.Tasks.Task<ClinicaMedica.ServiceReference1.Consulta[]> ListarTodasConsultasPorPacienteAsync(int codigoPaciente) {
            return base.Channel.ListarTodasConsultasPorPacienteAsync(codigoPaciente);
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public ClinicaMedica.ServiceReference1.CompositeType GetDataUsingDataContract(ClinicaMedica.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ClinicaMedica.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(ClinicaMedica.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
